"""Add nightmode_enabled to groups

Revision ID: 8q1mpw1tzp4y
Revises: 2024_05_11_add_locked_media
Create Date: 2026-05-12T08:03:33.791434

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8q1mpw1tzp4y"
down_revision: str | None = "2024_05_11_add_locked_media"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column(
            "nightmode_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "nightmode_enabled")
    # ### end Alembic commands ###
