"""Add locked_media to groups

Revision ID: 2024_05_11_add_locked_media
Revises: 2024_01_10_comprehensive_feature_migration
Create Date: 2024-05-11 20:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from src.bot.alembic import op

# revision identifiers, used by Alembic.
revision: str = "2024_05_11_add_locked_media"
down_revision: str | None = "2024_01_10_comprehensive_feature_migration"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("locked_media", sa.JSON(), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "locked_media")
    # ### end Alembic commands ###
